public with sharing class QSN_03 {
    
/*
//Answer c
  an Apex trigger may execute more than once during what the user considers a single save because of the execution flow, when the execution flow execute it's check the balidation rules< the before flow< the before triffer< the after flow < the after trigger .
  so that the trigger may execute more than once.

// we can create a approch that check that if the trigger is already executed that not run again.so that we can prevent multiple execution of a trigger a time 

*/

}